// Code generated by "stringer -type=Grade"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[A-0]
	_ = x[B-1]
	_ = x[C-2]
	_ = x[D-3]
	_ = x[F-4]
}

const _Grade_name = "ABCDF"

var _Grade_index = [...]uint8{0, 1, 2, 3, 4, 5}

func (i Grade) String() string {
	if i < 0 || i >= Grade(len(_Grade_index)-1) {
		return "Grade(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Grade_name[_Grade_index[i]:_Grade_index[i+1]]
}
